### PR TITLE
fixed bug and made brain images nicer

### PR DESCRIPTION
**Pull request by mrbesen**

### CODE REVIEW

**Comment by fakefred** [comment]
Thank you! I am merging this right away.

Two questions remain. I don't understand (1) how `import re` solves the crash, or (2) what crash it solves.

**Comment by mrbesen** [comment]
here is a log of the crash i had.  (the same thing happens with jpg of cause)
I have python 3.6.9 installed.
```
~/git/memethesis-cli $>memethesis -i
? Select meme format:  drake
? Select type for panel 1:  Drake dislike
? Text for panel 1: (leave blank to abort)  a
Current panels:
1. Drake dislike: a

? Add another panel?  Yes
? Select type for panel 2:  Drake like
? Text for panel 2: (leave blank to abort)  b
Current panels:
1. Drake dislike: a
2. Drake like: b

? Add another panel?  No
This is a list of panels you have added to your meme:
Current panels:
1. Drake dislike: a
2. Drake like: b

? Display a preview of your meme?  No
? Any further modifications to make?  No
? Save meme to: (only .jpg supported)  out.png
Traceback (most recent call last):
  File "/home/user/.local/bin/memethesis", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/memethesis/__main__.py", line 64, in main
    interactive()
  File "/home/user/.local/lib/python3.6/site-packages/memethesis/interactive.py", line 236, in interactive
    if o else 'meme.jpg')
NameError: name 'I' is not defined
```

**Comment by fakefred** [comment]
Lemme check the changelogs for `re`.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fakefred** [comment]
That would be weird. I'm running Python 3.8. Anyway, `import re` seems like better practice, so let it be what doesn't break.

**Pull request merged**
